# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dot_prod": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://nived-spacei.github.io/comp_arith/"

git_url = "https://github.com/nived-spacei/comp_arith/tree/{branch}/"

def custom_doc_links(name): return None
