# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['dot_prod', 'ComplexNumber', 'sayHello']

# Cell
import math
def dot_prod(x,y):
    return x.real*y.real+x.imag*y.imag

# Cell
class ComplexNumber:
    '''Defining `complex` number'''

    def __init__(self, r=0, i=0):
        self.real = r
        self.imag = i

    def __repr__(self):
        return f'{self.real}+{self.imag}j'

    def get_data(self):
        return f'{self.real}+{self.imag}j'

# Cell
class sayHello:
    '''Say hello to someone'''

    def __init__(self, to):
        self.to = to

    def say(self):
        return 'Say hello to {}'.format(self.to)